print ("welcome to the python")
print ("USA")
print ("Japan")
print ("India")
print (0 * "\n")
print ("Welcome to Guru99")
print ("Welcome to", end = ' ')
print ("Python", end = "!" "\n")
print ("@ ", end = "Govind")